const { cmd } = require('../command');
const axios = require('axios');

cmd({
    pattern: "getpp",
    alias: ["pp", "profile"],
    desc: "Fetch user profile picture with style",
    category: "tools",
    filename: __filename
}, async (conn, mek, m, { from, q, reply, botFooter }) => {
    try {
        // Determine the target: prioritize reply, then mention, then typed number
        let target = m.quoted ? m.quoted.sender : (m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : q.replace(/[^0-9]/g, '') + '@s.whatsapp.net');
        
        if (!target || target.length < 10) {
            return reply("⚠️ *Popkid, I need a target! Reply to a message or provide a number.*");
        }

        const numberOnly = target.split('@')[0];
        await conn.sendMessage(from, { react: { text: "🔍", key: mek.key } });

        // Using your EliteProTech API
        const apiUrl = `https://eliteprotech-apis.zone.id/getpp?prompt=${numberOnly}`;
        const { data } = await axios.get(apiUrl);

        if (!data.status || !data.profilePicture) {
            return reply(`❌ *Privacy Alert*\n\nI couldn't fetch the DP for @${numberOnly}. They might have restricted their profile picture visibility.`, { mentions: [target] });
        }

        // Stylish Caption for the result
        const stylishMsg = `
✨ *𝐏𝐎𝐏𝐊𝐈𝐃-𝐌𝐃 𝐏𝐏 𝐃𝐎𝐖𝐍𝐋𝐎𝐀𝐃𝐄𝐑* ✨

👤 *𝐔𝐬𝐞𝐫:* @${numberOnly}
🔗 *𝐔𝐑𝐋:* ${data.profilePicture}

> *Generated by Popkid AI*
`.trim();

        await conn.sendMessage(from, {
            image: { url: data.profilePicture },
            caption: stylishMsg,
            mentions: [target],
            footer: botFooter || 'ᴘᴏᴘᴋɪᴅ ᴀɪ ᴋᴇɴʏᴀ 🇰🇪'
        }, { quoted: mek });

        await conn.sendMessage(from, { react: { text: "📸", key: mek.key } });

    } catch (err) {
        console.error(err);
        reply("🚀 *Popkid-MD Error:* API is currently unreachable or the number format is invalid.");
    }
});
